config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get '/questions/preview', to: 'questions#preview'
  get '/answers/preview', to: 'answers#preview'
  get '/answers/typeEntry', to: 'answers#typeEntry'

  devise_for :users
  root 'questions#index'
  
  resources :questions do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :answers
    resources :votes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :answers do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :votes, only: [:create, :destroy]
  end

end

#/questions/:id/votes/create


#/questions/:question_id/answers/:id/votes/create

#si le paso una url que requiere dos ids hago _path(vote_type, vote_type_id)

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :comments, as: :c_duty
  has_many :votes, as: :v_duty
  
  validates :name, :description, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  require 'uri'

  
  before_action :set_markdowm, only: [:show, :create, :new, :edit, :preview]

  def new
    if user_signed_in?
      @question = Question.new
      render :new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path(@question.id)
    else
      @typeEntry = 'qs'
      @entry = @question
      respond_to do |format|
        format.js {render 'answers/errors.js.erb'}
      end
    end
  end

  def preview
    @typeEntry = params[:typeEntry]
    if params[:name].present?
      @title = params[:name]
    else
      @title = ''
    end

    if params[:description].present?
      @description = params[:description]
    else
      @description = ''
    end
    respond_to do |format|
      #format.html
      format.js
    end
  end

  def index
    @questions = Question.order(id: :desc)
    if params[:question].present?
      search = params[:question]
      @questions = @questions.where("description ILIKE ? OR name ILIKE ?", "%#{search}%", "%#{search}%")
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    redirect_to questions_path
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:name, :description).merge(user_id: current_user.id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<h2><%= @question.new_record? ? "Create": "Edit" %> Question</h2>
<div class="well">
  <!-- Nav tabs -->
  <%= form_for @question, remote: true, class: "comment-form" do |f| %>
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#editor" aria-controls="editor" role="tab" data-toggle="tab" class="qs-editor">Editor</a>
      </li>
      <li>
        <a href="#preview" aria-controls="preview" role="tab" data-toggle="tab" class="qs-preview">Preview</a>
      </li>
    </ul>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="editor">
        <div class="well">
          <%= f.label :name do %>
            Titulo:
          <% end %>
          <h3>
           <%= f.text_field(:name, class: "text-field") %> 
          </h3>
          <div>
            <%= f.text_area(:description, cols: 60, rows: 3, class: "qs-form")  %>
          </div>
          <div class="qs-messages">
            <p>This text editor supports markdown</p>
          </div>
          <div>
            <%= f.submit @question.new_record? ? "Create Question": "Edit Question", class: "btn btn-primary" %>
          </div>
        </div> 
      </div>
      <div role="tabpanel" class="tab-pane" id="preview">
        <div class="well">
          <h3 class="qs-title-preview turquesa"></h3>
          <div class="qs-text-preview">
          </div>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/views/questions/_markdownEditor.html.erb
  <!-- type: answer / comment -->
  <div class="row">
    <% if user_signed_in? %>
      <!-- <h4 class="turquesa">Enter your <%= type %></h4> -->
      <% if type != "edit" %>
        <% clase = "collapse" %>
        <div>
          <button id="<%= letter %>-create" class="btn btn-primary <%= link  %>" type="button" data-toggle="collapse" data-target="#collapse<%= type %>" aria-expanded="false" aria-controls="collapse<%= type %>">
            Create <%= type_name %>
          </button>
        </div>
        <% else %>
          <% clase = "otra" %>
      <% end %>
      <div class="<%= clase %>" id="<%= clase  %><%= type %>">
        <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#editor<%= type %>" aria-controls="editor<%= type %>" role="tab" data-toggle="tab" class="<%= letter %>-editor">Editor</a>
          </li>
          <li role="presentation">
            <a href="#preview<%= type %>" aria-controls="preview<%= type %>" role="tab" data-toggle="tab" class="<%= letter  %>-preview">Preview</a>
          </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="editor<%= type %>">
            <div class="well">
              <%= form_for [type_obj, type_obj_new], :remote => true do |f| %>
                <div>
                  <%= f.text_area(:description, cols: 60, rows: 3, class: "#{letter}-form")  %>
                </div> 
                <div class="<%= letter  %>-messages">
                  <p>This text editor supports markdown</p>
                </div>
                <div><%= f.submit "Send  #{type_name} ", class: "btn btn-primary big-button" %></div>
              <% end %>
            </div> 
          </div>
          <div role="tabpanel" class="tab-pane" id="preview<%= type %>">
            <div class="well">
              <h3 class="<%= letter %>-title-preview turquesa"></h3>
              <div class="<%= letter %>-text-preview">
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/questions/_votes.html.erb
<% if user_signed_in? %>
    <% if @question.votes.pluck(:user_id).include?(current_user.id)  %>
      <div class="center">
        <span class="glyphicon glyphicon-chevron-up stack"  aria-hidden="true"></span>
        <span><%= @question.votes.size  %></span>
        <%= link_to question_vote_path(@question, @question.votes), method: :delete do %>
          <span class="glyphicon glyphicon-chevron-down"  aria-hidden="true"></span>
        <% end %>
      </div>
    <% else %>
      <div class="center">
        <%= link_to question_votes_path(@question), method: :post do %>
          <span class="glyphicon glyphicon-chevron-up"  aria-hidden="true"></span>
        <% end  %>
        <span><%= @question.votes.size  %></span>
        <span class="glyphicon glyphicon-chevron-down"  aria-hidden="true"></span>
      </div>
    <% end %>
<% else %>
  <div class="center">
    <%= link_to new_user_session_path, method: :get do %>
      <span class="glyphicon glyphicon-chevron-up"  aria-hidden="true"></span>
    <% end %>
    <span><%= @question.votes.size  %></span>
    <%= link_to new_user_session_path, method: :get do %>
      <span class="glyphicon glyphicon-chevron-down"  aria-hidden="true"></span>
    <% end %>
  </div>
<% end %>

app/views/questions/_votesQA.html.erb
<% if user_signed_in? %>
    <!-- evaluar si el usuario ya realizo un voto  -->
    <% if qa.votes.pluck(:user_id).include?(current_user.id)  %>
      <div class="center">
      <!-- se pinta de naranja -->
        <span class="glyphicon glyphicon-chevron-up stack"  aria-hidden="true"></span>
        <span><%= qa.votes.size  %></span>
        <!-- se habilita boton para eliminar voto -->
        <%= link_to delete_vote, method: :delete, remote: true do %>
          <span class="glyphicon glyphicon-chevron-down"  aria-hidden="true"></span>
        <% end %>
      </div>
    <% else %>
      <div class="center">
      <!-- como el usuario no ha votado se le permite hacerlo -->
        <%= link_to create_vote, method: :post, remote: true do %>
          <span class="glyphicon glyphicon-chevron-up"  aria-hidden="true"></span>
        <% end  %>
        <!-- boton para eliminar voto desactivado -->
        <span><%= qa.votes.size  %></span>
        <span class="glyphicon glyphicon-chevron-down"  aria-hidden="true"></span>
      </div>
    <% end %>
<% else %>
  <div class="center">
    <%= link_to new_user_session_path, method: :get do %>
      <span class="glyphicon glyphicon-chevron-up"  aria-hidden="true"></span>
    <% end %>
    <span><%= qa.votes.size  %></span>
    <%= link_to new_user_session_path, method: :get do %>
      <span class="glyphicon glyphicon-chevron-down"  aria-hidden="true"></span>
    <% end %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%= render partial: "questions/form" %>

app/views/questions/index.html.erb
<div class="container">
<div class="row search-form">
  <div class="col-lg-7">
    <!-- <div class='search-form'> -->
    <h3>Test if your question already exists...</h3>
    <%= form_tag(questions_path,  {:method => :get}) do %>
      <%= text_field_tag(:question, params[:question], placeholder: "Search...", class: 'text-field') %>
    <% end %>
  </div>
  <div class="col-lg-5">
    <%= link_to "Create your Question", new_question_path, class: 'btn btn-primary'%>
  </div>
    <!-- </div> -->
</div>
  <table class="mytable">
    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td>
            <div class="votes"><%= pluralize(question.votes.size, 'Vote') %></div>
          </td>
          <td>
            <div class="votes"><%= pluralize(question.answers.size, 'Answer') %></div>
          </td>
          <td>
            <div class="name">
              <h4><span><%= link_to question.name, question_path(question), class: 'title' %></span></h4>
              <p class="asked">Asked <%= question.user.email %> <%= time_ago_in_words(question.created_at)%> ago</p>
            </div>
          </td>
          <td >
            <div class="votes">
            <% if user_signed_in? %>
              <% if current_user.id == question.user_id %>
                <%= form_tag(question_path(question.id), method: :delete, data: { confirm: 'Are you sure you want to delete this question?' }) do%>
                  <%= button_tag( class: "btn icon-t pull-right") do %>
                    <span class="glyphicon glyphicon-trash"></span>
                  <% end %>          
                <% end %>
                <%= link_to edit_question_path(question.id), class: "btn icon-t pull-right" do  %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <% end %>
              <% end %>
            <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>


</div>

app/views/questions/new.html.erb
<%= render partial: "questions/form" %>

app/views/questions/preview.js.erb
$(".<%= escape_javascript(@typeEntry)%>-title-preview").html('<%= escape_javascript(render :html => raw(@markdown.render(@title))) %>')
$(".<%= escape_javascript(@typeEntry) %>-text-preview").html('<%= escape_javascript(render :html => raw(@markdown.render(@description))) %>')

app/views/questions/show.html.erb
<div class="container">
  <!-- Question -->
  <div class="row">
    <div class="col-md-2 col-lg-2 col-sm-2 col-xs-1">
    <!-- votos para las questions -->
      <%= render :partial => "questions/votesQA", :locals => {:delete_vote => question_vote_path(@question, @question.votes), :create_vote => question_votes_path(@question), :qa => @question} %>
    </div>
    <div class="col-md-10 col-lg-10 col-sm-10 col-xs-11">
      <h3 class="turquesa"><%= @question.name  %></h3>
      <div class="question gray">
        <%= render :html => raw(@markdown.render(@question.description)) %>
        <p class="asked"> Asked: <%= @question.user.email %> <%= time_ago_in_words(@question.created_at) %> ago
         <% if user_signed_in? %>
          <% if current_user.id == @question.user_id %>
            <%= form_tag(question_path(@question.id), method: :delete, data: { confirm: 'Are you sure you want to delete this question?' }) do%>
              <%= button_tag( class: "btn icon-t pull-right") do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>          
            <% end %>
            <%= link_to edit_question_path(@question.id), class: "btn icon-t pull-right" do  %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
          <% end %>
        <% end %>
        </p>
      </div>
      
      <ul class="comments-questions">
        <div class="container">
          <% if @question.comments.any? %>
            <% @question.comments.each do |comment| %>
              <%= render :partial => "comments/commentShowcq", :locals => {:comment => comment} %> 
            <% end %>
          <% end %>
        </div>
      </ul>
    
    <div>
    <!-- Crear un comentario a la question -->
      <div class="container">
        <%= render :partial => "questions/markdownEditor", :locals => {:type_name => "Comment for this question", :type => "#{@question.comments.count +1}", :type_obj => @question, :type_obj_new => @question.comments.new, :link => "link", :letter =>"cq"} %>
      </div>
    </div>
    </div>
  </div>
  
  <!-- Answers -->
    <h4 class="turquesa"><%= pluralize(@question.answers.size, 'Answer') %></h4>
      <ul class="answers-list">        
        <!-- Muestra todas las answers asociadas a una question  -->
        <% @question.answers.each do |answer| %>
          <%= render :partial => "answers/answerShow", :locals => {:answer => answer}%>
        <% end %>
      </ul>
  
  <!-- Create your answer -->
  <h4 class="turquesa">Enter your Answer</h4>

      <%= render :partial => "questions/markdownEditor", :locals => {:type_name => "Answer", :type => "Answer", :type_obj => @question, :type_obj_new => @question.answers.new, :link => "btn-lg big-button", :letter => "an" } %>
  </div>