config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get '/questions/preview', to: 'questions#preview'
  get '/answers/preview', to: 'answers#preview'
  get '/answers/typeEntry', to: 'answers#typeEntry'

  devise_for :users
  root 'questions#index'
  
  resources :questions do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :answers
    resources :votes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :answers do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :votes, only: [:create, :destroy]
  end

end

#/questions/:id/votes/create


#/questions/:question_id/answers/:id/votes/create

#si le paso una url que requiere dos ids hago _path(vote_type, vote_type_id)

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :c_duty, polymorphic: true
  belongs_to :user

  validates :description, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :set_markdowm, only: [:create, :new, :edit, :show]

  def new
  end

  def create
    if params.has_key?(:answer_id)
      @answer = Answer.find(params[:answer_id])
      @question_id = @answer.question.id
      @question = Question.find(@question_id)
      @comment = @answer.comments.new(comment_params)
    else
      @question_id = params[:question_id]
      @question = Question.find(@question_id)
      @comment = @question.comments.new(comment_params)
    end
    if @comment.save
      if params.has_key?(:answer_id)
        respond_to do |format|
          format.js {render 'comments/createca.js.erb'}
        end
      else
        respond_to do |format|
          format.js {render 'comments/createcq.js.erb'}
        end
      end
      
      # redirect_to @question
    else
      @comment.created_at = Time.now
      @typeEntry = session[:passed_variable]
      @entry = @comment
      respond_to do |format|
        format.js {render 'answers/errors.js.erb'}
      end
      # render "questions/show"
    end
  end

  def edit
    if params.has_key?(:answer_id)
      @answer = Answer.find(params[:answer_id])
      @question_id = @answer.question.id
      @question = Question.find(@question_id)
      @comment = @answer.comments.find(params[:id])

      render :edit
    else
      @question_id = params[:question_id]
      @question = Question.find(@question_id)
      @comment = @question.comments.find(params[:id])
      render :edit
    end
  end

  def update
    if params.has_key?(:answer_id)
      @answer = Answer.find(params[:answer_id])
      @question_id = @answer.question.id
      @question = Question.find(@question_id)
      @comment = @answer.comments.find(params[:id])
      @comment.update(comment_params)
      redirect_to question_path(@question_id)
    else
      @question_id = params[:question_id]
      @question = Question.find(@question_id)
      @comment = @question.comments.find(params[:id])
      @comment.update(comment_params)
      redirect_to question_path(@question_id)
    end
  end

  def destroy
    if params.has_key?(:answer_id)
      @answer = Answer.find(params[:answer_id])
      @question_id = @answer.question.id
      @question = Question.find(@question_id)
      @comment = @answer.comments.find(params[:id])
      @comment.destroy
    else
      @question_id = params[:question_id]
      @question = Question.find(@question_id)
      @comment = @question.comments.find(params[:id])
      @comment.destroy
    end
    respond_to do |format|
      format.js 
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:description).merge(user_id: current_user.id)
  end

  # def create_comment(comment_type, question_id)
  #   validate_comment(comment_type)
  #   redirect_to question_path(question_id)
  # end

  # def validate_comment(comment_type)
  #   # @comment = Comment.new(comment_params)
  #   # @comment.update_attribute(:c_duty, comment_type)

  #   @comment = Comment.new(comment_params)
  #   if @comment.save
  #     @comment.update_attribute(:c_duty, comment_type)
  #   else
  #     render "questions/show"
  #   end
  # end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_commentShowca.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <%= render :html => raw(@markdown.render(comment.description)) %>
  <p class="asked"> Commented: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at)%> ago
  <div class="alinear-icons">
    <% if user_signed_in? %>
      <% if current_user.id == comment.user_id %>
        <%= link_to edit_answer_comment_path(@answer.id, comment.id), class: "btn icon" do  %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= form_tag(answer_comment_path(@answer.id, comment.id), remote: true, method: :delete, data: { confirm: 'Are you sure you want to delete this question?' }) do%>
          <%= button_tag( class: "btn icon") do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>          
        <% end %>
      <% end %>
    <% end %>
    </div>
  </p>
</div>

app/views/comments/_commentShowcq.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <%= render :html => raw(@markdown.render(comment.description)) %>
  <p class="asked"> Commented: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago 
  <div class="alinear-icons">
  <% if user_signed_in? %>
    <% if current_user.id == comment.user_id %>
      <%= form_tag(question_comment_path(@question.id, comment.id), remote: true, method: :delete, data: { confirm: 'Are you sure you want to delete this question?' }) do%>
        <%= button_tag( class: "btn icon") do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>          
      <% end %>
      <%= link_to edit_question_comment_path(@question.id, comment.id), class: "btn icon" do  %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
    <% end %>
  <% end %>
  </div>
  </p>
</div>

app/views/comments/createca.js.erb
$('.answer-<%= @answer.id %>').append('<%= j render :partial => "comments/commentShowca", :locals => {:comment => @comment}%>')

app/views/comments/createcq.js.erb
$('.comments-questions').append('<%= j render :partial => "comments/commentShowcq", :locals => {:comment => @comment}%>')

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id%>').remove()

app/views/comments/edit.html.erb
<% if @answer %>
  <%= render :partial => "answers/markdownEditor", :locals => {:type_name => "Comment", :type => "new#{@answer.id}", :type_obj => @answer, :type_obj_new => @comment, :link => "btn-lg big-button", :letter => "ca", :edit => "edit" } %>
<% else %>
  <%= render :partial => "questions/markdownEditor", :locals => {:type_name => "Comment", :type => "edit", :type_obj => @question, :type_obj_new => @comment, :link => "btn-lg big-button", :letter => "cq" } %>
<% end %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>