config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get '/questions/preview', to: 'questions#preview'
  get '/answers/preview', to: 'answers#preview'
  get '/answers/typeEntry', to: 'answers#typeEntry'

  devise_for :users
  root 'questions#index'
  
  resources :questions do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :answers
    resources :votes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :answers do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :votes, only: [:create, :destroy]
  end

end

#/questions/:id/votes/create


#/questions/:question_id/answers/:id/votes/create

#si le paso una url que requiere dos ids hago _path(vote_type, vote_type_id)

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :comments, as: :c_duty
  has_many :votes, as: :v_duty
  belongs_to :user
  belongs_to :question

  validates :description, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :set_markdowm, only: [:create, :show, :edit, :new, :preview]

  
  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    if @answer.save
      #redirect_to question_path(params[:question_id])
      respond_to do |format|
        format.js
      end
    else
      @typeEntry = session[:passed_variable] 
      @entry = @answer
      respond_to do |format|
        format.js {render 'errors.js.erb'}
      end
    end
  end

  def typeEntry
    @typeEntry = params[:typeEntry]
    session[:passed_variable] = @typeEntry
  end

  def preview
    @typeEntry = params[:typeEntry]
    @answerId = params[:answerId]
    if params[:description].present?
      @description = params[:description]
    else
      @description = ''
    end
    respond_to do |format|
      #format.html
      format.js {render "answers/preview.js.erb"}
    end
  end

  def edit 
    @answer = Answer.find(params[:id]) 
    @question = Question.find(params[:question_id])
    render "answers/edit"
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)
    redirect_to question_path(params[:question_id])
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    respond_to do |format|
      format.js
    end
    # redirect_to question_path(params[:question_id])
  end

  private
  def answer_params
    params.require(:answer).permit(:description).merge(question_id: params[:question_id], user_id: current_user.id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answerShow.html.erb
<!-- muestra una answer -->
<li class="answer row" id="answer-<%= answer.id %>">
  <div class="col-md-2 col-lg-2 col-sm-2 col-xs-1">
  <%= render :partial => "questions/votesQA", :locals => {:delete_vote => answer_vote_path(answer, answer.votes), :create_vote => answer_votes_path(answer), :qa => answer}  %>
  </div>
  <div class="col-md-10 col-lg-10 col-sm-10 col-xs-11">            
    <div class="gray">
      <%= render :html => raw(@markdown.render(answer.description)) %>
      <p class="asked">Answered: <%= answer.user.email %> <%= time_ago_in_words(answer.created_at)%> ago
      <div class="answer-icons">
      <% if user_signed_in? %>
        <% if current_user.id == answer.user_id %>
          <%= form_tag(question_answer_path(@question.id, answer.id), remote: true, method: :delete, data: { confirm: 'Are you sure you want to delete this question?' }) do%>
            <%= button_tag( class: "btn icon-t pull-right") do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>          
          <% end %>
          <%= link_to edit_question_answer_path(@question.id, answer.id), class: "btn icon-t pull-right" do  %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        <% end %>
      <% end %>
      </div>
      </p>
    </div>
    <div>
      <!-- Muestra los comentarios de una answer -->
      <div class="container">
        <ul class="answer-<%= answer.id %>">
          <% if answer.comments.any?   %>
          
            <% answer.comments.each do |comment| %>
              <%= render :partial => "comments/commentShowca", :locals => {:comment => comment, :@answer => answer}%>
            <% end %>
          
          <% end %>
        </ul>
      </div>
    </div>
  <!-- Boton para crear comentario a una answer  -->
  <div>
  <%= render :partial => "answers/markdownEditor", :locals => {:type_name => "Comment", :type => "new#{answer.id}", :type_obj => answer, :type_obj_new => answer.comments.new, :link => "link", :letter => "ca", :edit => "new" } %>
  </div>
  </li>

app/views/answers/_errorsShow.html.erb
<% if typeEntry %>
  <% if typeEntry.errors.any? %>    
    <div id="error_explanation">
      <h2>
        <%= pluralize(typeEntry.errors.count, "error") %> 
        prohibited this entry from being saved:
      </h2>
      <ul>
        <% typeEntry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/answers/_markdownEditor.html.erb
<!-- Este parcial solo se usa en los comments de una answer, para crearlos o editarlos -->
  <div class="row">
    <% if user_signed_in? %>
      <!-- si el usuario va a editar el comentario se muestra abierto osea sin la clase collapse de bootstrap -->
      <% if edit != "edit" %>
        <% clase = "collapse" %>
        <div>
          <button class="<%= letter %>-create btn btn-primary <%= link  %>" type="button" data-toggle="collapse" data-target="#collapse<%= type %>" aria-expanded="false" aria-controls="collapse<%= type %>">
            Create <%= type_name %>
          </button>
        </div>
        <% else %>
          <% clase = "otra" %>
      <% end %>
      <div class="<%= clase %>" id="<%= clase  %><%= type %>">
        <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#editor<%= type %>" aria-controls="editor<%= type %>" role="tab" data-toggle="tab" class="<%= letter %>-editor">Editor</a>
          </li>
          <li role="presentation">
            <a href="#preview<%= type %>" aria-controls="preview<%= type %>" role="tab" data-toggle="tab" class="<%= letter  %>-preview">Preview</a>
          </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="editor<%= type %>">
            <div class="well">
              <%= form_for [type_obj, type_obj_new], :remote => true do |f| %>
                <div>
                  <%= f.text_area(:description, cols: 60, rows: 3, class: "#{letter}-form-#{type_obj.id}")  %>
                </div> 
                <div class="<%= letter  %>-messages">
                  <p>This text editor supports markdown</p>
                </div>
                <div><%= f.submit "Send  #{type_name} ", class: "btn btn-primary big-button" %></div>
              <% end %>
            </div> 
          </div>
          <div role="tabpanel" class="tab-pane" id="preview<%= type %>">
            <div class="well">
              <h3 class="<%= letter %>-title-preview turquesa"></h3>
              <div class="<%= letter %>-text-preview-<%= type_obj.id %>">
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/answers/create.js.erb
$('.answers-list').append('<%= j render :partial => "answers/answerShow", :locals => {:answer => @answer}%>')

	 

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id%>').remove()

app/views/answers/edit.html.erb
<%= render :partial => "questions/markdownEditor", :locals => {:type_name => "Answer", :type => "edit", :type_obj => @question, :type_obj_new => @answer, :link => "btn-lg big-button", :letter => "an" } %>

app/views/answers/errors.js.erb
$('.<%= @typeEntry%>-messages').html('<%= j render :partial => "answers/errorsShow", :locals => {:typeEntry => @entry} %>')

app/views/answers/preview.js.erb
$(".<%= j @typeEntry %>-text-preview-<%= j @answerId %>").html('<%= escape_javascript(render :html => raw(@markdown.render(@description))) %>')