config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get '/questions/preview', to: 'questions#preview'
  get '/answers/preview', to: 'answers#preview'
  get '/answers/typeEntry', to: 'answers#typeEntry'

  devise_for :users
  root 'questions#index'
  
  resources :questions do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :answers
    resources :votes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :answers do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :votes, only: [:create, :destroy]
  end

end

#/questions/:id/votes/create


#/questions/:question_id/answers/:id/votes/create

#si le paso una url que requiere dos ids hago _path(vote_type, vote_type_id)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverStack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-static-top navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= questions_path  %>"><strong><span class="flow">Flow</span><span class="over">Over</span><span class="stack">Stack</span></strong></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Gastos<span class="sr-only">(current)</span></a></li> -->
            <% if user_signed_in? %>
              <li> <p>Hola <%=  current_user.email %></p></li>
              <li> <%= link_to("Log Out", destroy_user_session_path, method: :delete) %></li>
              <li> <%= link_to("Questions", questions_path) %></li>
            <% else %>
              <li> <%= link_to("Log In", new_user_session_path, method: :get) %></li>
              <li> <%= link_to("Sign Up", new_user_registration_path, method: :get) %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

<div id="wrap" >
  <div id="main" class="clear-top">
    <!-- <p>Your content here</p> -->
    <% flash.each do |name, msg| %>
      <!-- # New code (allow for flash elements to be arrays) -->
      <% if msg.class == Array %>
        <% msg.each do |message| %>
          <div id="error_explanation">
          <%= content_tag :div, message, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% else %>
      <div id="error_explanation">
        <%= content_tag :div, msg, :id => "flash_#{name} error_explanation" %>
      </div>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</div>
    
    <!-- <footer> -->
<!--       <div class="navbar navbar-inverse">

      </div> -->
<!--       <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2017 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
      </footer> -->
    <!-- </footer> -->



    <footer>
    <div class="navbar navbar-inverse">
      <div class="container-fluid">
        <p class="navbar-text pull-left">
          © 2017 Meli, Inc.
          <span class="glyphicon glyphicon-leaf" aria-hidden="true"></span>
        </p>
     </div>
    </div>
    </footer>
  
</body>
</html>